import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import BarraGovBr from "./components/GovBar";
import ChatBot from "./components/ChatBot";
import FixSuspence from "./components/FixSuspense";
import { AuthProvider } from "@/Context/AuthContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Portal Capes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
          <AuthProvider>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray1`}
        >
        <BarraGovBr />
        <Navbar />
        
        <FixSuspence>{children}</FixSuspence>
        <ChatBot />
        <Footer />
      </body>
        </AuthProvider>
    </html>
  );
}
